### ISSUE TITLE
qrng.physik.hu-berlin.de offline

### ISSUE THREAD

**Issue by kztork** [SeppPenner/QRNGHuBerlinTest#1]
It looks like the service  qrng.physik.hu-berlin.de is no longer available.
Are you able to connect? Or is there some alternative?

**Comment by SeppPenner** [comment]
I'm not able to connect either, seems like the domain is down completely? https://qrng.physik.hu-berlin.de/download is not reachable.

No, I don't have any alternatives yet. If anyone has, feel free to add them here...
